# Generated by Django 4.2.17 on 2025-01-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_sender_alter_topic_name_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.folder'),
        ),
    ]
